import Head from 'next/head'
import Image from 'next/image'
import { Montserrat } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Drohnengilde</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
          <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/drohnengilde.svg"
            alt="Drohnengilde Logo"
            width={500}
            height={120}
            priority
          />
          </div>

        <div className={styles.grid}>
          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={montserrat.className}>
              Drohne
            </h2>
            <p className={montserrat.className}>
              Hier erfährst du, womit wir fliegen.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={montserrat.className}>
              Footage
            </h2>
            <p className={montserrat.className}>
              Schau dir an, was wir bisher gemacht haben.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={montserrat.className}>
              Kontakt
            </h2>
            <p className={montserrat.className}>
              Hier lang für Fragen oder Terminvereinbarungen.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={montserrat.className}>
              Über uns
            </h2>
            <p className={montserrat.className}>
              Falls dich interessiert, wer wir sind.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
